### ISSUE TITLE
>exp doesn't work

### ISSUE THREAD

**Issue by TidalX** [veldlabs/miki-bot#610] opened 2020-02-20 17:33 UTC
**Describe the bug**
Miki Staging won't respond when you type the command >exp

**Expected behavior**
To show global level and experience

**Screenshots**
![image](https://user-images.githubusercontent.com/61288902/74962038-67be7880-540f-11ea-8f30-3ed2a1b48453.png)

**Comment by velddev** [comment] 2020-02-20 17:33
Duplicate of #609

**Closed as completed by velddev** 2020-02-20 17:33 UTC
Labels: bug, staging
