### ISSUE TITLE
Miki bot switched my proposals sent and recieved.

### ISSUE THREAD

**Issue by SavvageCabbage** [veldlabs/miki-bot#408] opened 2018-04-19 03:08 UTC
**What went wrong?**
Miki bot for some reason switched a ton of old proposals recieved and dumped them into the sent, please revert this and put all my proposals into recieved
**How do I reproduce this issue?**
by having miki for a long time

**Comment by xialight** [comment] 2018-04-19 09:46
Sorry but we can't switch every proposal. You have to do `>declinemarriage *` to clear all proposals.

**Comment by velddev** [comment] 2018-04-23 08:07
You can't reproduce this issue by having Miki for a long time. Sadly, I had to migrate data and it happened to not completely go as well. I hope this isn't a big issue for you. Since you didn't respond I am assuming you already moved on, thus I will close this issue.

**Closed as completed by velddev** 2018-04-23 08:07 UTC
